---
- name: apt-get update
  sudo: yes
  apt: update_cache=true cache_valid_time=3600
  when: should_run
  register: result_aptget_update
  until: result_aptget_update|success
  # Workaround https://github.com/ansible/ansible/issues/16868 and
  # increase default retry count
  retries: 20
  delay: 10
