---
- name: check for short-circuit
  raw: "> /dev/null command -v xz"
  register: installed
  ignore_errors: True
  changed_when: False

- name: check-for-short-circuit
  set_fact:
    should_run: "{{installed|failed or not xz_should_shortcircuit}}"

- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: install_package_names.yml
